# Generated by Django 5.0 on 2025-09-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='num_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
