# Generated by Django 5.0 on 2025-10-03 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='num_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='petition',
            name='whoVoted',
            field=models.ManyToManyField(blank=True, related_name='who_voted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
